/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module 'downshift' {
  declare type StateChangeTypes = {
    unknown: '__autocomplete_unknown__',
    mouseUp: '__autocomplete_mouseup__',
    itemMouseEnter: '__autocomplete_item_mouseenter__',
    keyDownArrowUp: '__autocomplete_keydown_arrow_up__',
    keyDownArrowDown: '__autocomplete_keydown_arrow_down__',
    keyDownEscape: '__autocomplete_keydown_escape__',
    keyDownEnter: '__autocomplete_keydown_enter__',
    clickItem: '__autocomplete_click_item__',
    blurInput: '__autocomplete_blur_input__',
    changeInput: '__autocomplete_change_input__',
    keyDownSpaceButton: '__autocomplete_keydown_space_button__',
    clickButton: '__autocomplete_click_button__',
    blurButton: '__autocomplete_blur_button__',
    controlledPropUpdatedSelectedItem: '__autocomplete_controlled_prop_updated_selected_item__',
  }
  declare type StateChangeValues =
    | '__autocomplete_unknown__'
    | '__autocomplete_mouseup__'
    | '__autocomplete_item_mouseenter__'
    | '__autocomplete_keydown_arrow_up__'
    | '__autocomplete_keydown_arrow_down__'
    | '__autocomplete_keydown_escape__'
    | '__autocomplete_keydown_enter__'
    | '__autocomplete_click_item__'
    | '__autocomplete_blur_input__'
    | '__autocomplete_change_input__'
    | '__autocomplete_keydown_space_button__'
    | '__autocomplete_click_button__'
    | '__autocomplete_blur_button__'
    | '__autocomplete_controlled_prop_updated_selected_item__'
  declare type Callback = () => void
  declare export interface DownshiftState<Item> {
    highlightedIndex: number | null;
    inputValue: string | null;
    isOpen: boolean;
    selectedItem: Item;
  }
  declare export interface DownshiftProps<Item> {
    defaultSelectedItem?: Item;
    defaultHighlightedIndex?: number | null;
    defaultInputValue?: string;
    defaultIsOpen?: boolean;
    itemToString?: (item: Item) => string;
    selectedItemChanged?: (prevItem: Item, item: Item) => boolean;
    getA11yStatusMessage?: (options: A11yStatusMessageOptions<Item>) => string;
    onChange?: (
      selectedItem: Item,
      stateAndHelpers: ControllerStateAndHelpers<Item>,
    ) => void;
    onSelect?: (
      selectedItem: Item,
      stateAndHelpers: ControllerStateAndHelpers<Item>,
    ) => void;
    onStateChange?: (
      options: StateChangeOptions<Item>,
      stateAndHelpers: ControllerStateAndHelpers<Item>,
    ) => void;
    onInputValueChange?: (
      inputValue: string,
      stateAndHelpers: ControllerStateAndHelpers<Item>,
    ) => void;
    stateReducer?: (
      state: DownshiftState<Item>,
      changes: StateChangeOptions<Item>,
    ) => StateChangeOptions<Item>;
    itemCount?: number;
    highlightedIndex?: number;
    inputValue?: string;
    isOpen?: boolean;
    selectedItem?: Item;
    render?: ChildrenFunction<Item>;
    children?: ChildrenFunction<Item>;
    id?: string;
    environment?: Environment;
    onOuterClick?: () => void;
    onUserAction?: (
      options: StateChangeOptions<Item>,
      stateAndHelpers: ControllerStateAndHelpers<Item>,
    ) => void;
  }
  declare export interface Environment {
    addEventListener: typeof undefined;
    removeEventListener: typeof undefined;
    document: Document;
  }
  declare export interface A11yStatusMessageOptions<Item> {
    highlightedIndex: number | null;
    inputValue: string;
    isOpen: boolean;
    itemToString: (item: Item) => string;
    previousResultCount: number;
    resultCount: number;
    selectedItem: Item;
  }
  declare export interface StateChangeOptions<Item> {
    type: StateChangeValues;
    highlightedIndex: number;
    inputValue: string;
    isOpen: boolean;
    selectedItem: Item;
  }
  declare export interface GetRootPropsOptions {
    refKey: string;
  }
  declare export type GetInputPropsOptions = {}
  declare export type GetLabelPropsOptions = {}
  declare export type GetButtonPropsOptions = {}
  declare interface OptionalExtraGetItemPropsOptions {
    [key: string]: any;
  }
  declare export type GetItemPropsOptions<Item> = {
    index?: number,
    item: Item,
  } & OptionalExtraGetItemPropsOptions
  declare export interface PropGetters<Item> {
    getRootProps: (options: GetRootPropsOptions) => any;
    getButtonProps: (options?: GetButtonPropsOptions) => any;
    getLabelProps: (options?: GetLabelPropsOptions) => any;
    getInputProps: (options?: GetInputPropsOptions) => any;
    getItemProps: (options: GetItemPropsOptions<Item>) => any;
  }
  declare export interface Actions<Item> {
    openMenu: (cb?: Callback) => void;
    closeMenu: (cb?: Callback) => void;
    toggleMenu: (cb?: Callback) => void;
    selectItem: (item: Item, otherStateToSet?: {}, cb?: Callback) => void;
    selectItemAtIndex: (
      index: number,
      otherStateToSet?: {},
      cb?: Callback,
    ) => void;
    selectHighlightedItem: (otherStateToSet?: {}, cb?: Callback) => void;
    setHighlightedIndex: (
      index: number,
      otherStateToSet?: {},
      cb?: Callback,
    ) => void;
    clearSelection: (cb?: Callback) => void;
    clearItems: () => void;
    reset: (otherStateToSet?: {}, cb?: Callback) => void;
    itemToString: (item: Item) => string;
  }
  declare export type ControllerStateAndHelpers<Item> = DownshiftState<Item> &
    PropGetters<Item> &
    Actions<Item>
  declare export type ChildrenFunction<Item> = (
    options: ControllerStateAndHelpers<Item>,
  ) => React.ReactNode
  declare export type DownshiftInterface<Item> = React.ComponentClass<
    DownshiftProps<Item>,
  > & {
    stateChangeTypes: StateChangeTypes,
  }
  declare var Downshift: DownshiftInterface<any>
  declare module.exports: typeof Downshift
}
