import {UseMultipleSelectionStateChangeTypes} from './types'

export declare const SelectedItemClick: UseMultipleSelectionStateChangeTypes.SelectedItemClick,
  SelectedItemKeyDownDelete: UseMultipleSelectionStateChangeTypes.SelectedItemKeyDownDelete,
  SelectedItemKeyDownBackspace: UseMultipleSelectionStateChangeTypes.SelectedItemKeyDownBackspace,
  SelectedItemKeyDownNavigationNext: UseMultipleSelectionStateChangeTypes.SelectedItemKeyDownNavigationNext,
  SelectedItemKeyDownNavigationPrevious: UseMultipleSelectionStateChangeTypes.SelectedItemKeyDownNavigationPrevious,
  DropdownKeyDownNavigationPrevious: UseMultipleSelectionStateChangeTypes.DropdownKeyDownNavigationPrevious,
  DropdownKeyDownBackspace: UseMultipleSelectionStateChangeTypes.DropdownKeyDownBackspace,
  DropdownClick: UseMultipleSelectionStateChangeTypes.DropdownClick,
  FunctionAddSelectedItem: UseMultipleSelectionStateChangeTypes.FunctionAddSelectedItem,
  FunctionRemoveSelectedItem: UseMultipleSelectionStateChangeTypes.FunctionRemoveSelectedItem,
  FunctionSetSelectedItems: UseMultipleSelectionStateChangeTypes.FunctionSetSelectedItems,
  FunctionSetActiveIndex: UseMultipleSelectionStateChangeTypes.FunctionSetActiveIndex,
  FunctionReset: UseMultipleSelectionStateChangeTypes.FunctionReset
